MODULE := object
LIB     = $(LIB_DIR)/lib$(MODULE).a

# ============================================================
#  源文件
# ============================================================

SRC := fuid/fuid.c
SRC += objkey/objkey.c
SRC += objmeta/objmeta.c
SRC += objtable/objtable.c

include ../../build/build.mk