MODULE := object
LIB     = $(LIB_DIR)/lib$(MODULE).a

# ============================================================
#  源文件
# ============================================================

SRC := object_init.c
SRC += fuid/fuid.c
SRC += objkey/objkey.c
SRC += objmeta/objmeta.c
SRC += objruntime/objruntime.c
SRC += objmgr/objmgr.c
SRC += objmgr/objmgr_ref.c
SRC += objmgr/objmgr_internal.c
SRC += objpool/objpool.c
SRC += objtable/objtable.c
SRC += obj_error.c
SRC += obj_sub.c

include ../../build/build.mk