MODULE := lsa
LIB     = $(LIB_DIR)/lib$(MODULE).a

# ============================================================
#  源文件
# ============================================================

SRC := internal/lsa_error.c
SRC += ops/lsa_handle.c
SRC += ops/lsa_namespace.c

include ../../build/build.mk