MODULE := lsa
LIB     = $(LIB_DIR)/lib$(MODULE).a

# ============================================================
#  源文件
# ============================================================

SRC := internal/lsa_error.c
SRC += ops/lsa_attr.c
SRC += ops/lsa_dir.c
SRC += ops/lsa_file.c
SRC += ops/lsa_fs.c
SRC += ops/lsa_xattr.c
SRC += ops/lsa_handle.c
SRC += ops/lsa_namespace.c

include ../../build/build.mk
