MODULE := lsa
LIB     = $(LIB_DIR)/lib$(MODULE).a

# ============================================================
#  源文件
# ============================================================

SRC := internal/lsa_error.c

include ../../build/build.mk