MODULE := runtime
LIB     = $(LIB_DIR)/lib$(MODULE).a

SRC := core/runtime_error.c
SRC += core/runtime_sub.c
SRC += core/runtime.c
SRC += core/runtime_session.c
SRC += core/runtime_namei.c
SRC += core/runtime_ops.c

include ../../build/build.mk
