MODULE := fops
LIB     = $(LIB_DIR)/lib$(MODULE).a

SRC := core/fops_error.c
SRC += core/fops_init.c
SRC += core/fops_helper.c
SRC += core/fops_spec.c
SRC += core/fops_dispatch.c
SRC += ops/fops_lookup.c
SRC += ops/fops_create.c
SRC += ops/fops_mkdir.c
SRC += ops/fops_mknod.c
SRC += ops/fops_attr.c
SRC += ops/fops_readdir.c
SRC += ops/fops_unlink.c
SRC += ops/fops_rmdir.c
SRC += ops/fops_rename.c
SRC += ops/fops_link.c
SRC += ops/fops_handle.c
SRC += ops/fops_rw.c
SRC += ops/fops_xattr.c
SRC += ops/fops_fs.c

include ../../build/build.mk
