MODULE := fops
LIB     = $(LIB_DIR)/lib$(MODULE).a

SRC := core/fops_error.c
SRC += core/fops_init.c
SRC += core/fops_helper.c
SRC += ops/fops_lookup.c
SRC += ops/fops_create.c
SRC += ops/fops_mkdir.c
SRC += ops/fops_getattr.c
SRC += ops/fops_readdir.c
SRC += ops/fops_unlink.c
SRC += ops/fops_rmdir.c
SRC += ops/fops_namespace_extra.c
SRC += ops/fops_file.c
SRC += ops/fops_attr_extra.c
SRC += ops/fops_xattr.c
SRC += ops/fops_fs.c

include ../../build/build.mk
