MODULE := fsc
LIB     = $(LIB_DIR)/lib$(MODULE).a

# ============================================================
# source files
# ============================================================

SRC := fsc_init.c
SRC += fsc_error.c
SRC += fsc_sub.c
SRC += fsid/fsid.c
SRC += namespace/namespace.c
SRC += nspool/nspool.c
SRC += fstable/fstable.c
SRC += fsmgr/fsmgr.c

include ../../build/build.mk
