MODULE := msh
LIB     = $(LIB_DIR)/lib$(MODULE).a

SRC := core/msh.c
SRC += core/msh_repl.c
SRC += core/msh_parse.c
SRC += core/msh_cmd_meta.c
SRC += core/msh_cmd_fs.c
SRC += core/msh_cmd_file.c

include ../../build/build.mk
