MODULE := namei
LIB     = $(LIB_DIR)/lib$(MODULE).a

SRC := core/namei_error.c
SRC += core/namei_sub.c
SRC += core/namei_init.c
SRC += core/namei_walk.c
SRC += ops/namei_ops.c

include ../../build/build.mk
