MODULE := common
LIB     = $(LIB_DIR)/lib$(MODULE).a

# ============================================================
#  源文件
# ============================================================

SRC := log/fs_log.c
SRC += error/fs_errno.c
SRC += hash/fs_hash.c
SRC += lock/fs_lock.c
SRC += os/fs_os.c
SRC += path/fs_path.c
SRC += trace/fs_trace.c
SRC += mempool/fs_mempool.c

include ../../build/build.mk
